### ISSUE TITLE
Doesn't work with draft-js-plugins-editor >= 2.0.0-beta6

### ISSUE THREAD

**Issue by esplo** [efloti/draft-js-mathjax-plugin#1]
# Problem

This plugin works fine with draft-js-plugins-editor <= 2.0.0-beta5, however, I got the following error with draft-js-plugins-editor >= 2.0.0-beta6.

`Uncaught TypeError: Cannot read property 'getEntity' of undefined`

# Cause

Exception will be raised in this line when `contentState` is null.
https://github.com/efloti/draft-js-mathjax-plugin/blob/master/src/utils.js#L64

Before beta5, contentState is Map instance.
After beta6, passed contentState is undefined.
Maybe how to handle "strategy" was changed after beta6 (I don't have deep insight for draft-js-plugins-editor, sorry).

Could you change the dependency in the package.json or fix it for beta10?

# Steps to reproduce
create a new react app, install draft-js-mathjax-plugin (1.3.3) with draft-js-plugins-editor beta6, then type $ in the Editor component

**Comment by efloti** [comment]
Thanks for the report. 

The problem is related to [change of API from draft-js](https://draftjs.org/docs/v0-10-api-migration.html#decorator-strategies-that-find-entities). 

The plugin use the new API, so it works with draft-js-plugins-editor>=2.0.0-beta10 (see the peerdependencies in package.json)

**Comment by efloti** [comment]
If you really need to resolve this, fork this repo and change _draft-js-mathjax-plugin/blob/master/src/utils.js_ from: 
```
export function findInlineTeXEntities(contentBlock, callback, contentState) {
  contentBlock.findEntityRanges(
    (character) => {
      const entityKey = character.getEntity()
      return (
        entityKey !== null &&
        contentState.getEntity(entityKey).getType() === 'INLINETEX'
      )
    },
    callback,
  )
}
 ```
to
```
export function findInlineTeXEntities(contentBlock, callback, contentState) {
  contentBlock.findEntityRanges(
    (character) => {
      const entityKey = character.getEntity()
      const type = contentState ?
         contentState.getEntity(entityKey).getType() :
         Entity.get(entityKey).getType()
      return type === 'INLINETEX'
    },
    callback,
  )
}
 ```
And add `Entity` in the 'draft-js' import.

**Comment by esplo** [comment]
I tried again, and I found the error was gone (maybe an wrong version of `draft-js-plugins-editor` was mixed into node_modules...).

Thank you so much for your investigation and suggestion!
