### ISSUE TITLE
When i render saved math from database more than one content state showing error

### ISSUE THREAD

**Issue by gmchaturvedi1** [efloti/draft-js-mathjax-plugin#3]
I just save as described by you to my database but when i render the content from the following editor componenet.

import React from 'react';
import Editor from 'draft-js-plugins-editor';
import createMathjaxPlugin from 'draft-js-mathjax-plugin'
import {convertFromRaw,EditorState} from 'draft-js';
import { fromJS} from 'immutable';
import forEach from 'lodash/forEach';
// const hashtagPlugin = createHashtagPlugin();
// const linkifyPlugin = createLinkifyPlugin();
const mathjaxPlugin = createMathjaxPlugin();
//const { InsertButton } = kaTeXPlugin;
//import './editor1.css';

const plugins = [
     mathjaxPlugin,
  // hashtagPlugin,
  // linkifyPlugin,
];

// forEach(rawContent.entityMap, function(value, key) {
//   value.data.mention = fromJS(value.data.mention)
// })

export default class MessageDisplay extends React.Component{

    constructor(props) {
        super(props);
        const blocks = convertFromRaw(this.props.msgObj);
        this.state = {editorState: EditorState.createWithContent(blocks)};
        //this.state = {editorState: EditorState.push(this.state.editorState, blocks, 'update-contentState')}
    }

onChange = (editorState) => {
    this.setState({editorState});
  };

    render(){
        return <div className="RichEditor-root message-display-root">
                <div className="RichEditor-editor message-display-editor">
                <Editor
                        editorState = {this.state.editorState}
                        readOnly={true}
                        plugins={plugins}
                         onChange ={ (editorState) => this.setState({editorState})}
                        />
                </div>
        </div>;
    }
}

when only one value it render correctly but when i just loop more than one value showing store.completion error.

Kindly help me out over this. 

Regards
gmchaturvedi

**Comment by efloti** [comment]
Hi, i don't really understand what you mean. Please, try to format your message (code, remove the commented lines ...) and explain better what you mean when you say:

> ... when i just loop more than one value...

, thanks.

**Comment by gmchaturvedi1** [comment]
Error thrown when displaying tex in readOnly Editor .i have data is question every question i am displaying through loop .if i display one question showing everything correct but when question is more than one then it is showing store.completion error.

my editor component is :

import React from 'react';
import Editor from 'draft-js-plugins-editor';
import createMathjaxPlugin from 'draft-js-mathjax-plugin'
import {convertFromRaw,EditorState} from 'draft-js';
import { fromJS} from 'immutable';
const mathjaxPlugin = createMathjaxPlugin();

const plugins = [
mathjaxPlugin,
];

export default class MessageDisplay extends React.Component{

constructor(props) {
    super(props);
    const blocks = convertFromRaw(this.props.msgObj);
    this.state = {editorState: EditorState.createWithContent(blocks)};
 
}
onChange = (editorState) => {
this.setState({editorState});
};

render(){
    return <div className="RichEditor-root message-display-root">
            <div className="RichEditor-editor message-display-editor">
            <Editor
                    editorState = {this.state.editorState}
                    readOnly={true}
                    plugins={plugins}
                     onChange ={ (editorState) => this.setState({editorState})}
                    />
            </div>
    </div>;
}
}



Reagrds
gmchaturvedi

**Comment by efloti** [comment]
If you use multiple instances of MessageDisplay on one page, you should call  createMathjaxPlugin inside his constructor (if not, each editor refer to the same instance of plugin ...).
```js
constructor(props) {
  super(props)
  this.plugins = [createMathJaxPlugin(), /*other call for other plugins*/]
  //...
}
//...
render() {
  return (<Editor /*...*/ plugins={this.plugins}/>)
}  
```
The same goes to other draft-js-plugins you would use.
I hope this help.

**Comment by gmchaturvedi1** [comment]
thanks you for your kind support its done as i am preparing education app so it is much needed functionality

**Comment by efloti** [comment]
Thanks. I hope the plugin will work fine for your use case.

**Comment by caominhtung1992** [comment]
TypeError: store.completion is not a function
